// This file will be auto-generated by the Supabase CLI
// Run `npm run supabase:types` to generate the latest types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      admins: {
        Row: {
          id: string
          email: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          email: string
          role?: string
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          role?: string
          created_at?: string
        }
        Relationships: []
      }
      members: {
        Row: {
          id: string
          name: string
          school_id: string
          organization_id: string
          submission_url: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          school_id: string
          organization_id: string
          submission_url: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          school_id?: string
          organization_id?: string
          submission_url?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "members_organization_id_fkey"
            columns: ["organization_id"]
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "members_school_id_fkey"
            columns: ["school_id"]
            referencedRelation: "schools"
            referencedColumns: ["id"]
          }
        ]
      }
      organizations: {
        Row: {
          id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
        }
        Relationships: []
      }
      schools: {
        Row: {
          id: string
          name: string
          organization_id: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          organization_id: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          organization_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "schools_organization_id_fkey"
            columns: ["organization_id"]
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
